language: ruby
cache: bundler

matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 3.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.0"
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 3.0"
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
    - rvm: 2.1.6
      env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"

script: 'bundle exec rake tests'

notifications:
  email:
    on_failure: change
    on_success: never
